- name: Install nginx
  hosts: remotehosts
  become: true
  tags: nginx
  diff: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        update_cache: true
        name: nginx

- name: Copy playbook test
  hosts: localhost
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        dest: hello
        content: world